apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-deployment
  namespace: video-to-audio-converter
  labels:
    app: converter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: converter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: converter
          image: gabzsz/mp3_converter:0.1.6
          envFrom:
            - configMapRef:
                name: converter-configmap
            - secretRef:
                name: converter-secret
